name: Get Webbing
favicon: null
layout_spectrum: 0.7650257654022425
typography_spectrum: 0.35754973883740604
title: Get Webbing
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#404040'
    - '#ffffff'
    - '#9eaace'
    - '#0000ff'
    - '#00ffff'
  brandStrength: 0.25
  lightness: 0.125
  saturation: 1
  rhythmicContrast: 0
purpose: []
